/** Legacy thin/noindex blog → 301 destinations (S08). */
export const LEGACY_BLOG_REDIRECTS: Array<{ source: string; destination: string }> = [
  { source: "/blog/aggiorna-sito-vecchio-piu-30-contatti-per-imprese-gemona", destination: "/blog" },
  { source: "/blog/app-router-nextjs-15-tutorial-developer-italiani", destination: "/blog" },
  { source: "/blog/automatizza-sito-web-newsletter-e-form-per-lead-udine-milano", destination: "/blog" },
  { source: "/blog/case-study-sito-pmi-milano-remoto-da-gemona", destination: "/blog" },
  { source: "/blog/come-creare-ecommerce-nextjs-gemona-del-friuli-guida-2026", destination: "/servizi" },
  { source: "/blog/come-un-sito-web-aumenta-vendite-per-pmi-milano-solaro", destination: "/blog" },
  { source: "/blog/costi-sito-web-2026-quanto-spendere-a-udine-per-risultati-top", destination: "/costo-sito-web" },
  { source: "/blog/ecommerce-dropshipping-lancia-negozio-online-da-gemona-facile", destination: "/servizi" },
  { source: "/blog/freelance-vs-agenzia-e-wordpress-perche-scegliere-sito-custom", destination: "/perche-noi" },
  { source: "/blog/google-my-business-sito-web-visibilita-gratuita-gemona-friuli", destination: "/comuni" },
  { source: "/blog/integrazione-whatsapp-su-sito-contatti-facili-per-negozi-milano", destination: "/servizi" },
  { source: "/blog/landing-responsive-tailwind-nextjs-esempi-solaro-udine", destination: "/servizi/landing-ads" },
  { source: "/blog/marketing-digitale-pmi-sito-social-per-crescere-solaro", destination: "/blog" },
  { source: "/blog/netlify-vs-vercel-deploy-per-freelance-gemona", destination: "/blog" },
  { source: "/blog/nextjs-vs-wordpress-per-business-friulani-e-milanesi", destination: "/friuli" },
  { source: "/blog/ottimizza-performance-nextjs-per-utenti-fvg", destination: "/friuli" },
  { source: "/blog/perche-il-tuo-business-a-udine-ha-bisogno-di-un-sito-web-nel-2026", destination: "/udine" },
  { source: "/blog/pwa-progressive-web-app-sito-come-app-per-utenti-friulani", destination: "/friuli" },
  { source: "/blog/recensioni-google-sul-sito-piu-fiducia-clienti-lombardia", destination: "/blog" },
  { source: "/blog/seo-on-page-nextjs-top-ranking-udine-milano", destination: "/blog" },
  { source: "/blog/siti-web-sicuri-https-proteggi-clienti-udine-da-hacker-2026", destination: "/blog" },
  { source: "/blog/siti-web-veloci-piu-clienti-per-negozi-gemona-friuli", destination: "/blog" },
  { source: "/blog/sito-internet-professionale-guida-semplice-per-artigiani-lombardi", destination: "/servizi/artigiani" },
  { source: "/blog/sito-web-con-blog-piu-visibilita-google-per-udine-gratis", destination: "/blog" },
  { source: "/blog/sito-web-ecommerce-facile-vendi-online-da-milano-senza-complicazioni", destination: "/servizi" },
  { source: "/blog/sito-web-multilingua-per-turisti-e-imprese-fvg-lombardia", destination: "/friuli" },
  { source: "/blog/sito-web-personalizzato-vs-template-quale-per-il-tuo-negozio-friulano", destination: "/friuli" },
  { source: "/blog/trasforma-visitatori-in-clienti-segreti-siti-web-efficaci-lombardia", destination: "/blog" },
  { source: "/blog/vantaggi-sito-web-mobile-cattura-clienti-in-movimento-fvg", destination: "/friuli" },
  { source: "/blog/vercel-per-siti-veloci-casi-studio-udine-lombardia", destination: "/blog" },
  { source: "/blog/web-trends-2026-friuli-lombardia-nextjs-custom", destination: "/friuli" },
];
