export const processPage = {
  eyebrow: "Processo",
  title: "Da un'idea a qualcosa di reale.",
  subtitle: "Ogni progetto parte da un'idea.",
  body: "La trasformo in una soluzione digitale attraverso un processo chiaro, condiviso e costruito intorno ai tuoi obiettivi.",
  thread: "Prima capiamo. Poi progetto. Poi costruisco.",
  stack: [
    "DISCOVERY",
    "STRATEGY",
    "DESIGN",
    "DEVELOPMENT",
    "LAUNCH",
    "SUPPORT",
  ] as const,
} as const;

export const processPhases = [
  {
    number: "01",
    title: "Discovery",
    headline: "Prima di costruire, ascoltiamo.",
    body: "Prima di parlare di codice, design o tecnologia, vogliamo capire il progetto.",
    intro: "Analizziamo:",
    items: [
      "cosa fai",
      "chi sono i tuoi clienti",
      "cosa vuoi ottenere",
      "quali problemi vuoi risolvere",
      "cosa esiste già",
      "cosa manca",
    ],
    closing: "Non parto dalla tecnologia. Parto dal problema.",
  },
  {
    number: "02",
    title: "Strategy",
    headline: "Diamo una direzione all'idea.",
    body: "Una volta capito il progetto, definiamo come trasformarlo in qualcosa di concreto.",
    intro: "Decidiamo:",
    items: [
      "struttura",
      "funzionalità",
      "contenuti",
      "tecnologia",
      "integrazioni",
      "percorso dell'utente",
    ],
    closing: "La tecnologia viene dopo la strategia.",
  },
  {
    number: "03",
    title: "Design",
    headline: "Prima lo immaginiamo insieme. Poi lo costruisco.",
    body: "Trasformo la strategia in un'esperienza visiva.",
    intro: "Ci occupiamo di:",
    items: ["UI", "UX", "Responsive", "Interazioni", "Identità visiva"],
    note: "L'obiettivo non è semplicemente creare qualcosa di bello.",
    closing: "Deve essere bello da vedere e semplice da utilizzare.",
  },
  {
    number: "04",
    title: "Development",
    headline: "Qui l'idea prende vita.",
    body: "È il momento in cui design e strategia diventano un prodotto reale.",
    intro: "A seconda del progetto posso utilizzare:",
    items: [
      "Next.js",
      "React",
      "TypeScript",
      "Node.js",
      "Shopify",
      "API",
      "Database",
      "Automazioni",
    ],
    question: "Codice o piattaforma?",
    closing: "Scelgo ciò che ha più senso per il progetto.",
  },
  {
    number: "05",
    title: "Test & Launch",
    headline: "Prima di pubblicare, controlliamo tutto.",
    body: "Il progetto viene testato su dispositivi e situazioni diverse.",
    intro: "Controlliamo:",
    items: [
      "Responsive",
      "Performance",
      "Funzionalità",
      "Form",
      "Link",
      "SEO tecnico",
      "Compatibilità",
      "Errori",
    ],
    closing: "Si pubblica.",
  },
  {
    number: "06",
    title: "Support",
    headline: "Il lancio non è la fine.",
    body: "Un progetto digitale può continuare a crescere.",
    intro: "Dopo la pubblicazione posso occuparmi di:",
    items: [
      "aggiornamenti",
      "manutenzione",
      "nuove funzionalità",
      "ottimizzazione",
      "assistenza",
      "automazioni",
      "evoluzione del progetto",
    ],
    closing: "Costruisco pensando anche a ciò che verrà dopo.",
  },
] as const;

export const processFlexible = {
  title: "Ogni progetto è diverso.",
  body: "Non uso lo stesso processo per ogni cliente. La struttura rimane chiara, ma strumenti, tecnologia e livello di personalizzazione cambiano in base al progetto.",
  types: [
    { label: "Template", href: "/servizi" },
    { label: "Custom", href: "/servizi" },
    { label: "E-commerce", href: "/servizi" },
    { label: "Web App", href: "/servizi" },
    { label: "Automation", href: "/servizi" },
    { label: "Digitalizzazione", href: "/servizi" },
  ],
} as const;

export const processCta = {
  title: "Hai un progetto in mente?",
  body: "Parto dalla prima cosa: parlarne.",
  cta: "Inizia un progetto",
} as const;
