export type ToolCategory =
  | "seo-audit"
  | "converter"
  | "content"
  | "utility"
  | "image"
  | "document"
  | "tracking";

export type ToolItem = {
  slug: string;
  name: string;
  category: ToolCategory;
  summary: string;
  intent: string;
  ready: "ui-ready" | "coming-soon";
};

export const toolCategoryLabels: Record<ToolCategory, string> = {
  "seo-audit": "SEO e Analisi Sito",
  converter: "Convertitori",
  content: "Contenuti e Copy",
  utility: "Utility Sviluppo",
  image: "Immagini",
  document: "Documenti",
  tracking: "Tracking e Marketing",
};

export const toolsCatalog: ToolItem[] = [
  {
    slug: "simulatore-roi-sito-web",
    name: "Simulatore ROI sito web",
    category: "tracking",
    summary: "Stima ritorno potenziale del progetto web.",
    intent: "Valutare impatto economico del sito.",
    ready: "ui-ready",
  },
  {
    slug: "simulatore-roi-seo-locale",
    name: "Simulatore ROI SEO locale",
    category: "tracking",
    summary: "Proiezione lead da posizionamento locale.",
    intent: "Pianificare investimenti SEO territoriali.",
    ready: "ui-ready",
  },
  {
    slug: "calcolatore-break-even-digitale",
    name: "Calcolatore break-even digitale",
    category: "tracking",
    summary: "Quando l'investimento web si ripaga.",
    intent: "Capire soglia minima di conversioni.",
    ready: "ui-ready",
  },
  {
    slug: "calcolatore-cpc-vs-seo",
    name: "Calcolatore CPC vs SEO",
    category: "tracking",
    summary: "Confronta acquisizione a pagamento e organica.",
    intent: "Scegliere mix canali più sostenibile.",
    ready: "ui-ready",
  },
  {
    slug: "stimatore-lead-organici",
    name: "Stimatore lead da traffico organico",
    category: "tracking",
    summary: "Stima lead mensili da click e conversion rate.",
    intent: "Tradurre traffico in opportunità reali.",
    ready: "ui-ready",
  },
  {
    slug: "calcolatore-conversion-rate-obiettivo",
    name: "Calcolatore conversion rate obiettivo",
    category: "tracking",
    summary: "Conversion rate richiesto per target lead.",
    intent: "Definire KPI realistici di funnel.",
    ready: "ui-ready",
  },
  {
    slug: "calcolatore-valore-lead",
    name: "Calcolatore valore lead",
    category: "tracking",
    summary: "Stima valore medio di ogni contatto.",
    intent: "Misurare qualità e priorità dei canali.",
    ready: "ui-ready",
  },
  {
    slug: "audit-seo-on-page-rapido",
    name: "Audit SEO on-page rapido",
    category: "seo-audit",
    summary: "Controllo base title, H1, description, headings.",
    intent: "Identificare fix SEO immediati.",
    ready: "coming-soon",
  },
  {
    slug: "checker-title-description",
    name: "Checker title e meta description",
    category: "seo-audit",
    summary: "Verifica lunghezza e leggibilità snippet.",
    intent: "Evitare truncation nei risultati Google.",
    ready: "coming-soon",
  },
  {
    slug: "serp-snippet-preview",
    name: "SERP snippet preview",
    category: "seo-audit",
    summary: "Anteprima risultati Google desktop/mobile.",
    intent: "Ottimizzare CTR organico.",
    ready: "ui-ready",
  },
  {
    slug: "generatore-meta-tag",
    name: "Generatore meta tag",
    category: "seo-audit",
    summary: "Proposta automatica title e description.",
    intent: "Velocizzare produzione metadati SEO.",
    ready: "ui-ready",
  },
  {
    slug: "generatore-schema-json-ld",
    name: "Generatore schema JSON-LD",
    category: "seo-audit",
    summary: "Crea markup strutturato per pagine web.",
    intent: "Migliorare comprensione semantica del sito.",
    ready: "ui-ready",
  },
  {
    slug: "validatore-robots-txt",
    name: "Validatore robots.txt",
    category: "seo-audit",
    summary: "Controllo sintassi e direttive principali.",
    intent: "Prevenire blocchi di crawling involontari.",
    ready: "ui-ready",
  },
  {
    slug: "generatore-sitemap-xml",
    name: "Generatore sitemap.xml",
    category: "seo-audit",
    summary: "Costruisce sitemap da elenco URL.",
    intent: "Facilitare discovery delle pagine.",
    ready: "ui-ready",
  },
  {
    slug: "verifica-canonical",
    name: "Verifica canonical URL",
    category: "seo-audit",
    summary: "Controlla canonical duplicati o assenti.",
    intent: "Ridurre cannibalizzazione e duplicazione.",
    ready: "ui-ready",
  },
  {
    slug: "analyzer-struttura-heading",
    name: "Analyzer struttura heading",
    category: "seo-audit",
    summary: "Mappa H1-H6 e gerarchia dei titoli.",
    intent: "Correggere struttura semantica della pagina.",
    ready: "ui-ready",
  },
  {
    slug: "keyword-difficulty-estimator",
    name: "Keyword difficulty estimator",
    category: "seo-audit",
    summary: "Stima competitività delle keyword.",
    intent: "Scegliere target keyword sostenibili.",
    ready: "ui-ready",
  },
  {
    slug: "keyword-clustering",
    name: "Keyword clustering tool",
    category: "content",
    summary: "Raggruppa keyword per intento e topic.",
    intent: "Progettare struttura pagine e contenuti.",
    ready: "ui-ready",
  },
  {
    slug: "generatore-piano-editoriale",
    name: "Generatore piano editoriale SEO",
    category: "content",
    summary: "Crea roadmap contenuti multi-settimana.",
    intent: "Pubblicare con costanza e coerenza.",
    ready: "ui-ready",
  },
  {
    slug: "content-brief-generator",
    name: "Content brief generator",
    category: "content",
    summary: "Brief SEO completo per articolo/pagina.",
    intent: "Accelerare produzione contenuti utili.",
    ready: "ui-ready",
  },
  {
    slug: "generatore-faq-seo",
    name: "Generatore FAQ SEO",
    category: "content",
    summary: "FAQ da query e intento utente.",
    intent: "Aumentare copertura long-tail.",
    ready: "ui-ready",
  },
  {
    slug: "generatore-slug-seo",
    name: "Generatore slug SEO-friendly",
    category: "content",
    summary: "Normalizza URL leggibili e ottimizzati.",
    intent: "Migliorare chiarezza URL e click.",
    ready: "ui-ready",
  },
  {
    slug: "keyword-density-checker",
    name: "Keyword density checker",
    category: "content",
    summary: "Misura distribuzione keyword nel testo.",
    intent: "Evitare over-optimization.",
    ready: "ui-ready",
  },
  {
    slug: "checker-leggibilita-italiano",
    name: "Checker leggibilità italiano",
    category: "content",
    summary: "Analizza facilità di lettura del copy.",
    intent: "Migliorare UX e chiarezza contenuti.",
    ready: "ui-ready",
  },
  {
    slug: "generatore-alt-text",
    name: "Generatore ALT text immagini",
    category: "content",
    summary: "Proposta alternative text accessibili.",
    intent: "Migliorare accessibilità e image SEO.",
    ready: "ui-ready",
  },
  {
    slug: "image-converter",
    name: "Image converter (JPG/PNG/WebP/AVIF)",
    category: "image",
    summary: "Converti immagini tra formati principali.",
    intent: "Ottimizzare performance media.",
    ready: "ui-ready",
  },
  {
    slug: "image-compressor",
    name: "Image compressor",
    category: "image",
    summary: "Riduci peso immagini con quality slider.",
    intent: "Migliorare tempi caricamento pagine.",
    ready: "ui-ready",
  },
  {
    slug: "image-resizer",
    name: "Image resizer",
    category: "image",
    summary: "Ridimensiona immagini per canale/uso.",
    intent: "Preparare asset per web e social.",
    ready: "ui-ready",
  },
  {
    slug: "background-remover",
    name: "Background remover",
    category: "image",
    summary: "Rimozione sfondo automatica da immagine.",
    intent: "Produrre asset commerciali rapidamente.",
    ready: "ui-ready",
  },
  {
    slug: "generatore-favicon",
    name: "Generatore favicon",
    category: "image",
    summary: "Crea favicon da logo o immagine.",
    intent: "Rafforzare brand e consistenza browser.",
    ready: "ui-ready",
  },
  {
    slug: "svg-png-converter",
    name: "SVG <-> PNG converter",
    category: "image",
    summary: "Converti asset vettoriali e raster.",
    intent: "Supportare workflow design e sviluppo.",
    ready: "ui-ready",
  },
  {
    slug: "pdf-compressor",
    name: "PDF compressor",
    category: "document",
    summary: "Riduci peso PDF mantenendo qualità utile.",
    intent: "Caricare documenti più velocemente.",
    ready: "ui-ready",
  },
  {
    slug: "pdf-merge-split",
    name: "PDF merge/split",
    category: "document",
    summary: "Unisci o separa pagine PDF.",
    intent: "Gestire documenti in modo pratico.",
    ready: "ui-ready",
  },
  {
    slug: "ocr-immagine-testo",
    name: "OCR immagine -> testo",
    category: "document",
    summary: "Estrai testo da screenshot e scansioni.",
    intent: "Recuperare contenuti rapidamente.",
    ready: "ui-ready",
  },
  {
    slug: "url-encoder-decoder",
    name: "URL encoder/decoder",
    category: "utility",
    summary: "Encode/decode URL e query string.",
    intent: "Debug e gestione parametri sicura.",
    ready: "ui-ready",
  },
  {
    slug: "base64-encoder-decoder",
    name: "Base64 encoder/decoder",
    category: "utility",
    summary: "Codifica e decodifica testi Base64.",
    intent: "Testing rapido payload e token.",
    ready: "ui-ready",
  },
  {
    slug: "json-formatter-validator",
    name: "JSON formatter/validator",
    category: "utility",
    summary: "Formatta e valida JSON in tempo reale.",
    intent: "Evitare errori API e configurazioni.",
    ready: "ui-ready",
  },
  {
    slug: "csv-to-json",
    name: "CSV to JSON converter",
    category: "converter",
    summary: "Trasforma dati tabellari in JSON.",
    intent: "Preparare dataset per tool e API.",
    ready: "ui-ready",
  },
  {
    slug: "cron-builder",
    name: "Cron expression builder",
    category: "utility",
    summary: "Crea schedule cron con linguaggio umano.",
    intent: "Ridurre errori su job pianificati.",
    ready: "ui-ready",
  },
  {
    slug: "regex-tester",
    name: "Regex tester",
    category: "utility",
    summary: "Prova regex con match in evidenza.",
    intent: "Velocizzare debug pattern testuali.",
    ready: "ui-ready",
  },
  {
    slug: "password-generator",
    name: "Password generator + checker",
    category: "utility",
    summary: "Genera password e verifica robustezza.",
    intent: "Migliorare sicurezza operativa base.",
    ready: "ui-ready",
  },
  {
    slug: "utm-builder",
    name: "UTM builder",
    category: "tracking",
    summary: "Genera URL tracciate per campagne.",
    intent: "Misurare performance canali marketing.",
    ready: "ui-ready",
  },
  {
    slug: "social-preview",
    name: "Social media post preview",
    category: "tracking",
    summary: "Anteprima Open Graph/Twitter card.",
    intent: "Aumentare CTR da condivisioni social.",
    ready: "ui-ready",
  },
  {
    slug: "wireframe-brief-generator",
    name: "Wireframe brief generator",
    category: "content",
    summary: "Brief strutturato per nuova landing page.",
    intent: "Allineare design e obiettivi commerciali.",
    ready: "ui-ready",
  },
  {
    slug: "website-launch-checklist",
    name: "Website launch checklist",
    category: "seo-audit",
    summary: "Checklist finale prima del go-live.",
    intent: "Ridurre errori di rilascio in produzione.",
    ready: "ui-ready",
  },
  {
    slug: "checker-core-web-vitals-base",
    name: "Checker Core Web Vitals (base)",
    category: "seo-audit",
    summary: "Confronta LCP, INP e CLS con le soglie Google.",
    intent: "Interpretare PageSpeed e Lighthouse senza API.",
    ready: "ui-ready",
  },
  {
    slug: "checker-broken-link",
    name: "Checker link rotti",
    category: "seo-audit",
    summary: "Testa URL http/https con richieste HEAD/GET dal server.",
    intent: "Individuare 404 e errori prima della messa online.",
    ready: "ui-ready",
  },
  {
    slug: "validatore-feed-rss",
    name: "Validatore feed RSS / Atom",
    category: "seo-audit",
    summary: "Controlli struttura RSS 2.0 e Atom; fetch sicuro degli URL pubblici.",
    intent: "Verificare title, channel/feed e item/entry prima della pubblicazione.",
    ready: "ui-ready",
  },
  {
    slug: "generatore-redirect-301",
    name: "Generatore redirect 301",
    category: "seo-audit",
    summary: "Snippet Apache, Nginx e JSON Next/Vercel da mappa vecchio→nuovo.",
    intent: "Migrare URL senza perdere ranking e backlink dopo redesign o merge.",
    ready: "ui-ready",
  },
  {
    slug: "generatore-robots-meta-directives",
    name: "Generatore robots meta directives",
    category: "seo-audit",
    summary: "Meta robots, googlebot e riga X-Robots-Tag da opzioni.",
    intent: "Controllare indicizzazione, snippet e anteprima senza errori di sintassi.",
    ready: "ui-ready",
  },
  {
    slug: "checker-accessibilita-base",
    name: "Checker accessibilità base",
    category: "seo-audit",
    summary: "Controlli markup WCAG-oriented su HTML incollato nel browser.",
    intent: "Primo screening locale su alt, label, link e landmark prima di audit completi.",
    ready: "ui-ready",
  },
  {
    slug: "color-contrast-checker",
    name: "Checker contrasto colori WCAG",
    category: "seo-audit",
    summary: "Rapporto di contrasto tra testo e sfondo secondo luminanza WCAG 2.x.",
    intent: "Verificare leggibilità e requisiti AA/AAA senza inviare palette a server esterni.",
    ready: "ui-ready",
  },
  {
    slug: "palette-generator-brand",
    name: "Generatore palette brand",
    category: "seo-audit",
    summary: "Scala primaria, accenti armonici e variabili CSS da un colore seme.",
    intent: "Allineare UI e design system a un brand color senza tool esterni.",
    ready: "ui-ready",
  },
  {
    slug: "generatore-open-graph-image",
    name: "Generatore immagine Open Graph",
    category: "seo-audit",
    summary: "PNG 1200×630 per og:image con titolo, gradiente e logo.",
    intent: "Preparare anteprime social coerenti con il brand senza Figma.",
    ready: "ui-ready",
  },
  {
    slug: "minificatore-html-css-js",
    name: "Minificatore HTML, CSS e JS",
    category: "utility",
    summary: "Compatto sicuro nel browser: commenti e spazi ridotti per snippet.",
    intent: "Preparare asset leggeri prima del deploy senza toolchain locale.",
    ready: "ui-ready",
  },
  {
    slug: "markdown-to-html",
    name: "Markdown to HTML",
    category: "converter",
    summary: "Trasforma Markdown (CommonMark + GFM) in frammento HTML nel browser.",
    intent: "Anteprima readme, snippet CMS e migrazioni contenuti senza server.",
    ready: "ui-ready",
  },
  {
    slug: "html-to-markdown",
    name: "HTML to Markdown",
    category: "converter",
    summary: "Da frammento HTML a Markdown strutturato con DOMParser nel browser.",
    intent: "Export da CMS/HTML verso readme, wiki e tool che consumano Markdown.",
    ready: "ui-ready",
  },
  {
    slug: "convertitore-unita-css",
    name: "Convertitore unità CSS",
    category: "converter",
    summary: "Da px, rem, em, viewport e unità assolute con riferimento 96px/in.",
    intent: "Allineare font-size e layout tra design, codice e browser.",
    ready: "ui-ready",
  },
  {
    slug: "webhook-tester",
    name: "Webhook tester",
    category: "utility",
    summary: "Prova GET/POST/PUT verso endpoint https pubblici dal server sicuro.",
    intent: "Verificare risposte di integrazioni e webhook di ingresso senza esporre SSRF.",
    ready: "ui-ready",
  },
  {
    slug: "dns-record-checker",
    name: "DNS record checker",
    category: "utility",
    summary: "Legge record DNS pubblici: A, AAAA, MX, TXT, NS, CNAME, SOA e CAA dal resolver del server.",
    intent: "Controllare mail exchange, nameserver, TXT (SPF/DKIM/DMARC) e coerenza zona senza CLI.",
    ready: "ui-ready",
  },
  {
    slug: "analizzatore-log-server",
    name: "Analizzatore log server",
    category: "utility",
    summary: "Sintesi access log: distribuzione stato HTTP, top percorsi, IP e metodi nel browser.",
    intent: "Scansionare estratti combinati Apache/Nginx o righe JSON strutturate senza inviare file al backend.",
    ready: "ui-ready",
  },
  {
    slug: "compressore-video-web",
    name: "Compressore video web",
    category: "converter",
    summary: "Riduci il peso di MP4 e WebM ricodificando con FFmpeg.wasm nel browser.",
    intent: "Preparare clip leggere per landing e social senza caricare i file su server esterni.",
    ready: "ui-ready",
  },
  {
    slug: "generatore-privacy-policy-base",
    name: "Generatore privacy policy base",
    category: "seo-audit",
    summary: "Bozza strutturata di informativa privacy GDPR per siti italiani nel browser.",
    intent: "Partire da uno scheletro leggibile prima del passaggio allo studio legale.",
    ready: "ui-ready",
  },
  {
    slug: "generatore-cookie-banner-copy",
    name: "Generatore cookie banner copy",
    category: "seo-audit",
    summary: "Testi italiani per banner cookie e primo livello CMP con link a policy.",
    intent: "Accelerare UX legale del consenso prima dell’implementazione tecnica.",
    ready: "ui-ready",
  },
  {
    slug: "estimatore-tempo-lettura",
    name: "Estimatore tempo di lettura",
    category: "content",
    summary: "Stima minuti e secondi da conteggio parole e WPM configurabile.",
    intent: "Mostrare durata lettura su articoli e newsletter senza invio al server.",
    ready: "ui-ready",
  },
];

export const toolsBySlug = new Map(toolsCatalog.map((tool) => [tool.slug, tool]));
